"""Postgres helpers for storing and querying user transactions.

The functions in this module create the database schema and provide async
helpers for inserting, summarising, listing, and deleting transactions.
"""

from __future__ import annotations

import os
import ssl
from decimal import Decimal
from typing import Any

import asyncpg

_pool: asyncpg.Pool | None = None
_DB_EXCEPTIONS = (
    asyncpg.PostgresError,
    asyncpg.InterfaceError,
    OSError,
    TimeoutError,
)


class DatabaseError(RuntimeError):
    """Raised when a database operation fails."""


def _database_url() -> str:
    """Return the configured Postgres connection URL."""
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL is missing from the environment.")
    return database_url


def _ssl_config() -> ssl.SSLContext | bool | None:
    """Return the SSL config used by asyncpg.

    Supabase requires SSL. The default "require" mode encrypts the connection
    without verifying the certificate chain, which matches many managed poolers.
    Use DATABASE_SSL=verify-full when the platform has the required CA chain.
    Use DATABASE_SSL=false for a local Postgres instance without SSL.
    """
    ssl_mode = os.getenv("DATABASE_SSL", "require").lower()
    if ssl_mode in {"0", "false", "no", "disable"}:
        return False
    if ssl_mode in {"verify", "verify-full", "true"}:
        return ssl.create_default_context()
    if ssl_mode in {"1", "require", "yes"}:
        return ssl._create_unverified_context()
    raise RuntimeError(
        "DATABASE_SSL must be one of: require, verify-full, false."
    )


async def _get_pool() -> asyncpg.Pool:
    """Return the active Postgres pool or fail clearly."""
    if _pool is None:
        raise DatabaseError("Database pool has not been initialised.")
    return _pool


def _to_float(value: Decimal | float | int | None) -> float:
    """Convert numeric database values to float for Discord display."""
    return float(value or 0)


def _to_transaction(row: asyncpg.Record) -> dict[str, Any]:
    """Convert a Postgres row into the dictionary shape used by the cog."""
    created_at = row["created_at"]
    return {
        "id": row["id"],
        "user_id": row["user_id"],
        "type": row["type"],
        "amount": _to_float(row["amount"]),
        "category": row["category"],
        "description": row["description"],
        "created_at": created_at.strftime("%Y-%m-%d %H:%M:%S"),
    }


async def init_db() -> None:
    """Initialise the Postgres pool, table, and indexes."""
    global _pool

    if _pool is None:
        _pool = await asyncpg.create_pool(
            dsn=_database_url(),
            min_size=1,
            max_size=5,
            command_timeout=30,
            ssl=_ssl_config(),
        )

    async with _pool.acquire() as connection:
        await connection.execute(
            """
            CREATE TABLE IF NOT EXISTS transactions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
                amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
                category TEXT NOT NULL,
                description TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        await connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_transactions_user_created
            ON transactions (user_id, created_at DESC, id DESC)
            """
        )


async def close_db() -> None:
    """Close the Postgres pool if it is open."""
    global _pool

    if _pool is not None:
        await _pool.close()
        _pool = None


async def ping_db() -> None:
    """Run a cheap health query against Postgres."""
    try:
        pool = await _get_pool()
        async with pool.acquire() as connection:
            await connection.execute("SELECT 1")
    except _DB_EXCEPTIONS as exc:
        raise DatabaseError("Database health check failed.") from exc


async def add_transaction(
    user_id: int,
    transaction_type: str,
    amount: float,
    category: str,
    description: str | None = None,
) -> int:
    """Store a transaction for the given user and return the created ID."""
    if transaction_type not in {"income", "expense"}:
        raise ValueError("transaction_type must be 'income' or 'expense'.")

    try:
        pool = await _get_pool()
        async with pool.acquire() as connection:
            transaction_id = await connection.fetchval(
                """
                INSERT INTO transactions (user_id, type, amount, category, description)
                VALUES ($1, $2, $3, $4, $5)
                RETURNING id
                """,
                user_id,
                transaction_type,
                amount,
                category,
                description,
            )
            return int(transaction_id)
    except _DB_EXCEPTIONS as exc:
        raise DatabaseError("Failed to add transaction.") from exc


async def get_summary(user_id: int) -> dict[str, float]:
    """Return a financial summary for the given user."""
    try:
        pool = await _get_pool()
        async with pool.acquire() as connection:
            row = await connection.fetchrow(
                """
                SELECT
                    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0) AS income,
                    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0) AS expenses
                FROM transactions
                WHERE user_id = $1
                """,
                user_id,
            )
    except _DB_EXCEPTIONS as exc:
        raise DatabaseError("Failed to fetch summary.") from exc

    income = _to_float(row["income"] if row else 0)
    expenses = _to_float(row["expenses"] if row else 0)
    return {
        "income": income,
        "expenses": expenses,
        "balance": income - expenses,
    }


async def get_history(user_id: int, limit: int = 10) -> list[dict[str, Any]]:
    """Return the most recent transactions for the given user."""
    limit = max(1, min(limit, 25))

    try:
        pool = await _get_pool()
        async with pool.acquire() as connection:
            rows = await connection.fetch(
                """
                SELECT id, user_id, type, amount, category, description, created_at
                FROM transactions
                WHERE user_id = $1
                ORDER BY created_at DESC, id DESC
                LIMIT $2
                """,
                user_id,
                limit,
            )
            return [_to_transaction(row) for row in rows]
    except _DB_EXCEPTIONS as exc:
        raise DatabaseError("Failed to fetch history.") from exc


async def delete_transaction(user_id: int, transaction_id: int) -> bool:
    """Delete a transaction by ID if it belongs to the user."""
    try:
        pool = await _get_pool()
        async with pool.acquire() as connection:
            result = await connection.execute(
                """
                DELETE FROM transactions
                WHERE id = $1 AND user_id = $2
                """,
                transaction_id,
                user_id,
            )
            return result == "DELETE 1"
    except _DB_EXCEPTIONS as exc:
        raise DatabaseError("Failed to delete transaction.") from exc
